code --install-extension abusaidm.html-snippets
code --install-extension blanu.vscode-styled-jsx
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension dzannotti.vscode-babel-coloring
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension eg2.tslint
code --install-extension Equinusocio.vsc-material-theme
code --install-extension flowtype.flow-for-vscode
code --install-extension idleberg.hopscotch
code --install-extension jaredly.reason-vscode
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension kisstkondoros.vscode-gutter-preview
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension leizongmin.node-module-intellisense
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension mikestead.dotenv
code --install-extension mohsen1.prettify-json
code --install-extension MS-CEINTL.vscode-language-pack-zh-hant
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.Go
code --install-extension ms-vscode.Theme-MarkdownKit
code --install-extension nwolverson.ide-purescript
code --install-extension nwolverson.language-purescript
code --install-extension octref.vetur
code --install-extension PeterJausovec.vscode-docker
code --install-extension PKief.material-icon-theme
code --install-extension raashida.fixthecode-vs
code --install-extension samverschueren.linter-xo
code --install-extension shinnn.stylelint
code --install-extension teabyii.ayu
code --install-extension vector-of-bool.cmake-tools
code --install-extension wart.ariake-dark
code --install-extension whizkydee.material-palenight-theme
code --install-extension yzane.markdown-pdf
code --install-extension yzhang.markdown-all-in-one
